FROM tsl0922/musl-cross
RUN git clone --depth=1 https://github.com/tsl0922/ttyd.git /ttyd \
    && cd /ttyd && env BUILD_TARGET=i686 WITH_SSL=true ./scripts/cross-build.sh

FROM i386/alpine
COPY --from=0 /ttyd/build/ttyd /usr/bin/ttyd
RUN apk add --no-cache bash tini
RUN apk add --no-cache openssh-client

RUN apk add curl git
RUN curl -LO https://dl.k8s.io/v1.19.0-rc.4/kubernetes-client-linux-386.tar.gz
RUN && tar -xzf kubernetes-client-linux-386.tar.gz  && chmod u+x ./kubernetes/client/bin/kubectl && mv ./kubernetes/client/bin/kubectl /bin/kubectl && rm kubernetes-client-linux-386.tar.gz

EXPOSE 7681

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["ttyd", "bash"]
